spring.profiles.active=local

# H2 Database configuration
#spring.datasource.url=jdbc:h2:~/a1ecommerce
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=sa

jdbc.url=jdbc:h2:~/a1ecommerce
jdbc.driverClassName=org.h2.Driver
jdbc.username=sa
jdbc.password=sa

# Properties that control the population of schema and data for a new data source
jdbc.initLocation=db/a1ecommerceH2.sql
jdbc.dataLocation=db/a1ecommerceDumpH2.sql

jpa.database=H2
hibernate.showSql=true
hibernate.dialect=org.hibernate.dialect.H2Dialect
hibernate.hbm2ddl.auto=validate
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.hbm2ddl.import_files=db/a1ecommerceH2.sql
hibernate.ejb.naming_strategy=org.hibernate.cfg.ImprovedNamingStrategy
	
init-db=true
